server:
  port: 8521
spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false    #设置不需要注册到 consul 中

#ribbon 负载均衡策略配置, service-producer为注册的服务名 (默认RoundRobinRule-轮询，RandomRule-随机)
service-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

#开启熔断器
feign:
  hystrix:
    enabled: true